dev/styling - Styling sidenavigation!
phoenixlan/phoenixcrew-v1 pull request #1
Opened 2022-09-11 15:31 UTC by HenrikEngen

:-)

2022-11-24 02:58 UTC, petterroea requested changes

2022-11-24 02:58 UTC, petterroea commented on src/container/sidebarCategory.jsx
> +
Remove this

2022-11-24 02:58 UTC, petterroea commented on src/pages/agenda/index.jsx
> +                        <InnerContainer flex="1">
Hvorfor er det to forms på samme side?

2022-11-24 02:58 UTC, petterroea commented on src/pages/dashboard.jsx
> +    return (
?

2022-11-24 02:58 UTC, petterroea commented on src/pages/event/list.jsx
> +                                    <Column flex="5">{ new Date(event.booking_time * 1000).toLocaleString('default', {dateStyle: 'short', timeStyle: 'short'}) }</Column>
Siden du bruker samme options på alle tre - vurder å legge det i en variabel

2022-12-29 03:36 UTC, petterroea commented on src/container/sidebar.jsx
> +/*
Remove

2022-12-29 03:36 UTC, petterroea commented on src/pages/agenda/index.jsx
>      //TODO not quite right, backend har ikke application state enda
Remove

2022-12-29 03:36 UTC, petterroea commented on src/pages/agenda/view.jsx
> +    /*const onSubmit = async (data) => {
Remove

2022-12-29 03:36 UTC, petterroea commented on src/pages/application/list.jsx
>      //TODO not quite right, backend har ikke application state enda
Remove

2022-12-29 03:36 UTC, petterroea commented on src/pages/seatmap/listSeatmaps.jsx
> +{/*
Remove

2022-12-29 03:36 UTC, petterroea commented on src/pages/ticket/tickets.jsx
> +                            /*
Remove

2022-12-29 03:36 UTC, petterroea commented on src/router/index.jsx
> +                            <NotAvailable />
Don't do this

2023-01-04 20:20 UTC, HenrikEngen commented
Til info: **application/view.jsx** mangler styling

2023-01-05 05:13 UTC, merged